# Generated by Django 5.0.6 on 2024-07-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainers',
            new_name='Employee',
        ),
    ]
